# Используем Docker-образ с установленным Go для выполнения шагов
image: golang:1.20

# Указываем стадии пайплайна
stages:
  - vet   # Проверка синтаксиса
  - test  # Запуск тестов
  - run   # Запуск приложения

# Шаг проверки синтаксиса
go-vet:
  stage: vet
  script:
    - echo "Запускаем проверку синтаксиса Go-кода..."
    - go vet ./...
  only:
    - main  # Выполняем на основной ветке или ветках для ревью

# Шаг тестирования
go-test:
  stage: test
  script:
    - echo "Запускаем тесты Go-кода..."
    - go test ./...
  only:
    - main  # Выполняем на основной ветке или ветках для ревью

# Шаг запуска приложения
go-run:
  stage: run
  script:
    - echo "Запускаем приложение и выводим ASCII-арт..."
    - go run cmd/main.go  # Запуск основного файла приложения
  only:
    - main  # Выполняем на основной ветке